[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=2592000, must-revalidate"
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=2592000, must-revalidate"
[[headers]]
  for = "*.png"
  [headers.values]
    Cache-Control = "public, max-age=2592000, must-revalidate"
[[headers]]
  for = "*.jpg"
  [headers.values]
    Cache-Control = "public, max-age=2592000, must-revalidate"
[[headers]]
  for = "*.ico"
  [headers.values]
    Cache-Control = "public, max-age=2592000, must-revalidate"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200